### ISSUE TITLE
请问楼主什么叫tone匹配？

### ISSUE THREAD

**Issue by huangjf11** [alingse/emoji-chengyu#8]
![image](https://github.com/alingse/emoji-chengyu/assets/43243253/eeb32e39-fde4-4d64-9f38-27499c08611b)
想请教下楼主，什么叫做去掉tone匹配。

谢谢🙏

**Comment by alingse** [comment]
@huangjf11 就是 音调, 因为通过汉字转拼音得到的拼音是  ā á ǎ à 带了声调  但是 emoji 标注的是不带声调的 a ，

所以需要去掉声调之后再匹配。

**Comment by alingse** [comment]
@huangjf11 很简单，你看这里的代码

https://github.com/alingse/emoji-chengyu/blob/master/emoji_chengyu/data.py#L7C1-L33C2 

```
TONE_MAP = {
    "ā": "a",
    "á": "a",
    "ǎ": "a",
    "à": "a",
    "ē": "e",
    "é": "e",
    "ě": "e",
    "è": "e",
    "ī": "i",
    "í": "i",
    "ǐ": "i",
    "ì": "i",
    "ō": "o",
    "ó": "o",
    "ǒ": "o",
    "ò": "o",
    "ū": "u",
    "ú": "u",
    "ǔ": "u",
    "ù": "u",
    "ü": "v",
    "ǖ": "v",
    "ǘ": "v",
    "ǚ": "v",
    "ǜ": "v"
}
```

直接看这个代码 replace 一下就好了。
